# ESG Scoring Dashboard Configuration
   
   data:
     raw_data_dir: "data/raw"
     processed_data_dir: "data/processed"
     external_data_dir: "data/external"
   
   companies:
     target_list: ["AAPL", "MSFT", "TSLA", "GOOGL", "AMZN", "META", "NVDA", "JPM", "JNJ", "PG"]
     max_companies_dev: 5
   
   apis:
     sec_edgar:
       rate_limit_delay: 0.1  # seconds between requests
       max_retries: 3
     
     yfinance:
       period: "5y"  # financial data lookback period
   
   scoring:
     weights:
       environmental: 0.33
       social: 0.33  
       governance: 0.34
   
   database:
     type: "sqlite"
     name: "esg_data.db"
     location: "data/processed/"